### ISSUE TITLE
Inkscape-figures watch has no response or log on MacOS

### ISSUE THREAD

**Issue by BerryTaylor** [gillescastel/inkscape-figures#12]
@pierreglaser 
sorry for bother you again, 
I reinstalled it for my default python, and all goes well if I do things we do the last day.
But I find that the svg cannot be saved as pdf and pdf_tex automatically, and when I run the command"Inkscape-figures watch"
there is not any response or log.
So what should I do to get the error report now?

**Comment by pierreglaser** [comment]
Hi. If you have a question or need some help, I encourage you to reach out to me directly rather than open an issue in the main repository, in order to avoid noise for the owner and the contributors. Feel free to close this and send me an email instead. If there really is a bug, then we shall open an issue.

**Comment by BerryTaylor** [comment]
Sure, sorry for my abrupt behavior!
